import type { Metadata } from "next";
import "@/sass/index.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Patty Ehinger Luxury Travel Advisory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
